import { DocPage } from "@/components/docs/DocPage";
export default function DocsPublishing() {
  return (
    <DocPage breadcrumb="Deploy › Publishing" title="Publishing Pages" description="Publish custom pages, blogs, AI-generated content, and websites to the public web.">
      <h2>Custom Pages</h2>
      <p>Pages created in Xstellar can be published with a unique slug at /x/:slug. Toggle publish status from the page editor.</p>
      <h2>Blogs</h2>
      <p>Write and publish blog posts with rich text editing, cover images, and tags. Published blogs are accessible at /published/:id.</p>
      <h2>AI Websites</h2>
      <p>Websites generated by the AI Website Generator can be published at /w/:slug with full HTML/CSS/JS support.</p>
      <h2>Music & Songs</h2>
      <p>AI-generated songs and music tracks can be published and shared via unique URLs.</p>
    </DocPage>
  );
}
